export const USERS_COLLECTION = 'users'
export const BOXES_COLLECTION = 'boxes'
export const CATEGORIES_COLLECTION = 'categories'
export const BRANDS_COLLECTION = 'brands'
export const PRODUCTS_COLLECTION = 'products'
export const ORDERS_COLLECTION = 'orders'
export const ADDRESSES_COLLECTION = 'addresses'
