export const FONTS = {
  abrilFatface: 'AbrilFatface-Regular',
  demi: 'FuturaNewDemi-Reg',
  light: 'FuturaNewLight-Reg',
  medium: 'FuturaNewMedium-Reg',
  quicksand: 'Quicksand-Regular',
  quicksandBold: 'Quicksand-Bold',
  quicksandLight: 'Quicksand-Light',
  quicksandMedium: 'Quicksand-Medium',
  josefinSans: 'JosefinSans-Regular',
  josefinSansBold: 'JosefinSans-Bold',
  josefinSansSemiBold: 'JosefinSans-SemiBold',
  inter: 'Inter-Regular',
  interBold: 'Inter-Bold',
  interLight: 'Inter-Light',
  interMedium: 'Inter-Medium',
  interSemiBold: 'Inter-SemiBold',
  system: 'System',
}
