require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
permissions_path = '../node_modules/react-native-permissions/ios'

target 'unboxme' do
  config = use_native_modules!
  rn_maps_path = '../node_modules/react-native-maps'
  use_react_native!(:path => config["reactNativePath"])

#   use_flipper!({ 'Flipper' => '0.74.0' })
  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'PanModal', '~> 1.2.7'
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'
  
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
