require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'unboxme' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  use_flipper!({ 'Flipper' => '0.74.0' })
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'
  pod 'PanModal', '~> 1.2.7'

  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end
