# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "./ios/unboxme.xcodeproj")
    match(type: "appstore")
    build_app(workspace: "./ios/unboxme.xcworkspace", scheme: "unboxme",  clean: false, export_method: "app-store")
    upload_to_testflight
  end
  lane :upload_firebase do
      firebase_app_distribution(debug: true, app: "1:759842823698:ios:bac6ef82bae23dedd602cb")
    end
end
