default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :ios do
    increment_build_number(xcodeproj: "./ios/unboxme.xcodeproj")
    match(type: "appstore")
    build_app(workspace: "./ios/unboxme.xcworkspace", scheme: "unboxme",  clean: false, export_method: "app-store")
    upload_to_testflight
  end
  lane :android do
    gradle(
        task: 'bundle',
        project_dir: 'android/',
        build_type: 'Release',
      )
    firebase_app_distribution(debug: true, app: "1:759842823698:ios:bac6ef82bae23dedd602cb")
  end
end
