default_platform(:ios)

lane :increment_build do
  sh("./increment_build.sh")
end

lane :getVersion do
  my_package_json = read_json(json_path: "./package.json")
  my_package_json[:version]
end

lane :getBuildNumber do
  my_package_json = read_json(json_path: "./package.json")
  my_package_json[:buildNumber]
end

lane :handle_changelog do
  version = getVersion()
  read_changelog(section_identifier: "[#{version}]")
end

lane :notify_slack do
  version = getVersion()
  buildNumber = getBuildNumber()
  slack(message: "*Unboxme #{version} (#{buildNumber})* was distributed for #{lane_context[SharedValues::PLATFORM_NAME]}", default_payloads: [])
end

platform :iOS do
  desc "Push a new beta build to TestFlight"
  lane :build_and_upload do
    match(type: "development", app_identifier: ["com.unboxme.app"])
    build_app(workspace: "./ios/unboxme.xcworkspace", scheme: "unboxme",  clean: true, export_method: "app-store")
    changelog_data = handle_changelog
    upload_to_testflight(skip_waiting_for_build_processing: true)
#     firebase_app_distribution(app: ENV["FIREBASE_IOS_ID"], firebase_cli_token: ENV["FIREBASE_TOKEN"], release_notes: changelog_data)
    notify_slack
  end
end

platform :android do
  lane :build do
    gradle(
      project_dir: './android',
      task: 'bundle',
      build_type: 'Release'
    )
  end
  lane :build_and_upload do
    build
    changelog_data = handle_changelog
#     upload_to_play_store(track: 'internal', skip_upload_apk: true, release_status: 'draft')
    firebase_app_distribution(app: ENV["FIREBASE_ANDROID_ID"], firebase_cli_token: ENV["FIREBASE_TOKEN"], release_notes: changelog_data, android_artifact_path: "android/app/build/outputs/bundle/release/app-release.aab")
    notify_slack
  end
end

lane :release_all do
  increment_build
  sh "fastlane android build_and_upload"
  sh "fastlane ios build_and_upload"
end
